#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: /Users/jian/local
#  file: /Users/jian/local/sell.log/
#  level:
#    com.jian.LoggerTest: debugspring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.127.128:3306/sell?characterEncodin=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8080
wechat:
  mpAppId: wx42ca0ac180b16b54
  mpAppSecret: 259227a975f41a3ad90221c481e5d578
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/jian/h5.p12
  notifyUrl: http://selldemo.natapp1.cc/sell/pay/notify

